export const GET_USER_POSTS_REQUEST = "GET_USER_POSTS_REQUEST";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_FAIL = "GET_USER_POSTS_FAIL";
export const GET_CURRENT_POST_STATE = "GET_CURRENT_POST_STATE";

export const SET_COMMENT_REQUEST = "SET_COMMENT_REQUEST";
export const SET_COMMENT_SUCCESS = "SET_COMMENT_SUCCESS";
export const SET_COMMENT_FAIL = "SET_COMMENT_FAIL";

export const SET_LIKE_REQUEST = "SET_LIKE_REQUEST";
export const SET_LIKE_SUCCESS = "SET_LIKE_SUCCESS";
export const SET_LIKE_FAIL = "SET_LIKE_FAIL";

export const POST_UPLOAD_REQUEST = "POST_UPLOAD_REQUEST";
export const POST_UPLOAD_SUCCESS = "POST_UPLOAD_SUCCESS";
export const POST_UPLOAD_FAIL = "POST_UPLOAD_FAIL";
