export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST ";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS ";
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL ";

export const GET_RANDOM_USERS_REQUEST = "GET_RANDOM_USERS_REQUEST";
export const GET_RANDOM_USERS_SUCCESS = "GET_RANDOM_USERS_SUCCESS";
export const GET_RANDOM_USERS_FAIL = "GET_RANDOM_USERS_FAIL";

export const SET_FOLLOW_REQUEST = "SET_FOLLOW_REQUEST";
export const SET_FOLLOW_SUCCESS = "SET_FOLLOW_SUCCESS";
export const SET_FOLLOW_FAIL = "SET_FOLLOW_FAIL";

export const IMAGE_FILE_UPLOAD_REQUEST = "IMAGE_FILE_UPLOAD_REQUEST ";
export const IMAGE_FILE_UPLOAD_SUCCESS = "IMAGE_FILE_UPLOAD_SUCCESS ";
export const IMAGE_FILE_UPLOAD_FAIL = "IMAGE_FILE_UPLOAD_FAIL ";

