export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const IMAGE_FILE_UPLOAD_REQUEST = "IMAGE_FILE_UPLOAD_REQUEST ";
export const IMAGE_FILE_UPLOAD_SUCCESS = "IMAGE_FILE_UPLOAD_SUCCESS ";
export const IMAGE_FILE_UPLOAD_FAIL = "IMAGE_FILE_UPLOAD_FAIL ";

export const POST_UPLOAD_BY_USER_ID_REQUEST = "POST_UPLOAD_BY_USER_ID_REQUEST";
export const POST_UPLOAD_BY_USER_ID_SUCCESS = "POST_UPLOAD_BY_USER_ID_SUCCESS";
export const POST_UPLOAD_BY_USER_ID_FAIL = "POST_UPLOAD_BY_USER_ID_FAIL";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const SET_COMMENT_REQUEST = "SET_COMMENT_REQUEST";
export const SET_COMMENT_SUCCESS = "SET_COMMENT_SUCCESS";
export const SET_COMMENT_FAIL = "SET_COMMENT_FAIL";

export const SET_LIKE_REQUEST = "SET_LIKE_REQUEST";
export const SET_LIKE_SUCCESS = "SET_LIKE_SUCCESS";
export const SET_LIKE_FAIL = "SET_LIKE_FAIL";
